### ISSUE TITLE
(Feature Request) .lrc support

### ISSUE THREAD

**Issue by ghost** [tcode-dev/ThinMP_Android_Kotlin#2]
- Lyrics file support when it is placed in the same folder as the song being played and also has the same name as the music file.
- Example - songname.mp3, songname.lrc.
- For reference, you can check out the mi music app.
- I am only talking about the full screen lyrics that appear when you click on the cover image.
- Not the lyrics that appear below the song and artist's name.
- And maybe a song, lyrics button at the top to change between lyric and song rather than clicking on the image.

### Example Images

![20230831_165214](https://github.com/tcode-dev/ThinMP_Android_Kotlin/assets/129925515/e43bd11c-86f6-469a-81be-a3517b631788)

---

![20230831_165253](https://github.com/tcode-dev/ThinMP_Android_Kotlin/assets/129925515/e5ae4f1a-18dc-47b9-9ba3-945047fd85ad)

**Comment by tcode-dev** [comment]
No plans to do so at this time.
